version: '3'

dotenv:
- .env
# - .env

includes:
  # k3d: ./config/tasks/k3d.yaml
  k3d: ./posts/k3d-intro/k3d-intro.yaml
  external-dns: ./posts/PGK-part-3/tasks.yaml
  coredns: ./posts/coredns/tasks.yaml

silent: true

tasks:

  k3d-intro-insecure:
    desc: Start the k3d cluster
    cmds:
    - task: k3d:cluster-create

  k3d-intro:
    desc: Start the k3d cluster
    cmds:
    - task: k3d:cluster-create
    - task: k3d:dns
    - task: k3d:certs

  external-dns:
    desc: Run the external-dns project
    cmds:
    - task: external-dns:pkg-part-3

  coredns:
    desc: Run the codedns project
    cmds:
    - task: coredns:dns-test

  help:
    desc: Show help
    cmds:
    - task --list
