version: '3'

dotenv:
- .env
# - .env

includes:
  # k3d: ./config/tasks/k3d.yaml
  k3d: ./posts/k3d-intro/k3d-intro.yaml
  

silent: true

tasks:

  start-k3d:
    desc: Start the k3d cluster
    cmds:
    - task: k3d:cluster-create

  start-secure:
    desc: Start the k3d cluster
    cmds:
    - task: start-k3d
    - task: k3d:dns
    - task: k3d:certs
  pkg-part-3:
    desc: Build the project
    dir: posts/PGK-part-3
    cmds:
    - echo "please makke sure the domain-anem in the annotations is correct / or your kubecontxt is set to the correct cluster for your domain"
    - echo $KUBECTL_CONTEXT
    - echo $PWD
    - kubectl apply -n default -f $PWD



  help:
    desc: Show help
    cmds:
    - task --list
