version: '3'

# silent: true

dotenv:
- .env

includes:
  # utils
  helm: ./config/tasks/templates-helm.yaml
  templates: ./config/tasks/templates.yaml
  # tests
  test: ./config/tasks/test.yaml
  # posts
  k3d: ./posts/k3d-intro/k3d-intro.yaml
  external-dns: ./posts/PGK-part-3/tasks.yaml
  coredns: ./posts/coredns/tasks.yaml
  argocd: ./posts/argocd/tasks.yaml
  nginx: ./posts/nginx/tasks.yaml
  # common tools for this repo
  tools: ./config/tasks/tools.yaml
  config-managment: ./posts/config/tasks.yaml
  monitoring-n-logging: ./posts/monitoring-n-logging/tasks.yaml
  vault: ./posts/vault-eso/tasks.yaml
  awx: ./posts/awx/tasks.yaml
  cicd-toolz: ./posts/cicd-toolz/tasks.yaml
silent: true

tasks:

  k3d-intro-insecure:
    desc: Start the k3d cluster
    cmds:
    - task: k3d:cluster-create

  k3d-intro:
    desc: Start the k3d cluster
    cmds:
    - task: k3d:cluster-create
    - task: k3d:dns
    - task: k3d:certs

  external-dns:
    desc: Run the external-dns project
    cmds:
    - task: external-dns:pkg-part-3

  coredns:
    desc: Run the codedns project
    cmds:
    - task: coredns:dns-test

  start-argocd:
    desc: Deploy argocd project
    cmds:
    - task: argocd:secret
    - task: argocd:repo
    - task: argocd:install

  start-nginx:
    desc: Deploy nginx project
    cmds:
    - task: nginx:install

  so-far:
    desc: Run all tasks
    cmds:
    - task: k3d-intro
    - task: start-argocd
    - task: start-nginx
    - task: monitoring-n-logging:all

  config-managment:
    desc: Run all config-managment tasks
    cmds:
    - task: config-managment:install
    
  help:
    desc: Show help
    cmds:
    - task --list
