version: '3'

# silent: true

dotenv:
- .env

includes:
  # utils
  helm: ./config/tasks/helm.yaml
  templates: ./config/tasks/templates.yaml
  utils: ./config/tasks/utils.yaml
  # tests
  test: ./config/tasks/test.yaml
  # posts
  k3d: ./posts/k3d-intro/k3d-intro.yaml
  external-dns: ./posts/PGK-part-3/tasks.yaml
  coredns: ./posts/coredns/tasks.yaml
  argocd: ./posts/argocd/tasks.yaml
  ingress-nginx: ./posts/ingress-nginx/Taskfile.yaml
  pre-commit: ./posts/pre-commit/Taskfile.yaml
  # common tools for this repo
  tools: ./config/tasks/tools.yaml

  # common tools foor configuration managment   
  
  # config-managment: ./posts/config/tasks.yaml
  reloader: ./posts/config/reloader/Taskfile.yaml
  descheduler: ./posts/config/descheduler/Taskfile.yaml
  reflector: ./posts/config/reflector/Taskfile.yaml

  vault: ./posts/vault-eso/tasks.yaml
  sealed-secrets: ./posts/sealed-secrets/Taskfile.yaml

  awx: ./posts/awx/tasks.yaml
  # applications / packages
  cicd-toolz: ./posts/cicd-toolz/tasks.yaml
  
  # helm chart registry
  chartmeusem: ./posts/chartmeusem/tasks.yaml
  
  # scaling
  goldilocks: ./posts/goldilocks/Taskfile.yaml

  # policy
  gatekeeper: ./posts/gatekeeper/Taskfile.yaml
  gatekeeper-pm: ./posts/gatekeeper-policy-manager/Taskfile.yaml

  # observability
  monitoring-n-logging: ./posts/monitoring-n-logging/tasks.yaml

  # iac
  iac: ./posts/terraform/Taskfile.yaml

  # whoami-demo-app via nginx
  whoami: ./posts/whoami/Taskfile.yaml
  
tasks:

  cluster-create:
    desc: Start the k3d cluster
    cmds:
    - task: k3d:cluster-template
    - task: k3d:cluster-create
    - task: k3d:dns
    - task: k3d:certs

  external-dns:
    desc: Run the external-dns project
    cmds:
    - task: external-dns:pkg-part-3

  coredns:
    desc: Run the codedns project
    cmds:
    - task: coredns:dns-test

  argocd:
    desc: Deploy argocd project
    cmds:
    - task: argocd:install
    - task: argocd:secret
    - task: argocd:repo

  ingress-nginx:
    desc: Deploy nginx project
    cmds:
    - task: ingress-nginx:install

  config-managment:
    desc: Run all config-managment tasks
    cmds:
    - task: reloader:install
    - task: reflector:install
    - task: descheduler:install
  
  sealed-secrets:
    desc: Run all sealed-secrets tasks
    cmds:
    - task: cluster-create
    - task: sealed-secrets:install-kubeseal
    - task: sealed-secrets:create-private-key
    - kubectl apply -k .config/sealed-secrets
    - task: sealed-secrets:local-apply

  goldilocks-minimal:
    desc: Run the goldilocks project
    cmds:
    - task: cluster-create
    - task: ingress-nginx:install
    - task: reflector:install
    - task: reloader:install
    - task: goldilocks:install
    # - open https://goldilocks.k8s.localhost

  opa-gatekeeper:
    desc: Run the opa-gatekeeper project
    cmds:
    - task: goldilocks-minimal
    - task: gatekeeper:full-run
    - task: gatekeeper-pm:full-run
    # - open https://gpm.k8s.localhost
  
  opa-gatekeeper-demo:
    - task: gatekeeper:create-constraint-teample
    - task: gatekeeper:create-constraint
    - task: gatekeeper:test-constraint-expect-failure
    - task: gatekeeper:test-constraint-expect-success
  
  opa-gatekeeper-demo-cleanup:
    - task: gatekeeper:delete-constraint
    - task: gatekeeper:delete-constraint-template
  

  run-awx:
    vars:
      ADDITIONAL_HOSTS: "awx.k8s.localhost"
    desc: Run the awx project
    cmds:
    # - task: cluster-create
    # - kubectl apply -k .config/tls
    # - task: argocd
    # - task: config-managment
    # - task: ingress-nginx
    # - task: awx:secret
    # - task: awx:install
    - task: awx:run-awx-playbook

  run-tests:
    desc: Run tests
    cmds:
      - task: test:helm-wrapper

  destroy-env:
    desc: Destroy the k3d cluster
    cmds:
    - k3d cluster delete $CLUSTER_NAME

  help:
    desc: Show help
    cmds:
    - task --list
