---
version: '3'

# silent: true

dotenv:
- .env

includes:

  # utils
  utils: 
    taskfile: ./config/tasks/utils.yaml

  # suites
  app: 
    taskfile: ./config/tasks/apps.yml
    
  # suites
  suite: 
    taskfile: ./config/tasks/suites.yml

tasks:

  # debug
  default:
    desc: Debug the environment
    cmds:
    - task: help

  run-tests:
    desc: Run tests
    cmds:
      - task: test:helm-wrapper
  
  help:
    desc: Show help
    cmds:
    - task --list

  # k3d
  k3d:cluster:create:
    desc: Start the k3d cluster
    cmds:
    - task: suite:k3d:cluster-template
    - task: suite:k3d:cluster-create
    - task: suite:k3d:dns
    - task: suite:k3d:certs

  k3d:cluster:delete:
    desc: Destroy the k3d cluster
    cmds:
    - k3d cluster delete $CLUSTER_NAME

  # production-rediness-series | service discovery

  external-dns:eks:demo:
    desc: Run the external-dns project
    requires: &exdns_req
      vars:
        - DEMO_EKS_ACCOUNT_ID
        - DEMO_EKS_REGION
        - DEMO_EKS_CLUSTER_NAME
    cmds:
    - task: suite:production-rediness-external-dns:default
      vars:
        KUBECTL_CONTEXT: "arn:aws:eks:{{.DEMO_EKS_REGION}}:{{.DEMO_EKS_ACCOUNT_ID}}:cluster/{{.DEMO_EKS_CLUSTER_NAME}}"
  
  external-dns:eks:demo:cleanup:
    desc: Cleanup the external-dns project
    requires: *exdns_req
    cmds:
    - task: suite:production-rediness-external-dns:cleanup
      vars:
        KUBECTL_CONTEXT: "arn:aws:eks:{{.DEMO_EKS_REGION}}:{{.DEMO_EKS_ACCOUNT_ID}}:cluster/{{.DEMO_EKS_CLUSTER_NAME}}"

  # issue with core dns debugging

  coredns:
    desc: Run the codedns project
    cmds:
    - task: suite:coredns:dns-test

  # argocd - quick start for demo's

  argocd:
    desc: Deploy argocd project
    cmds:
    - task: app:argocd:install
    - task: app:argocd:secret
    - task: app:argocd:repo

  # ingress-nginx
  
  ingress-nginx:
    desc: Deploy nginx project
    cmds:
    - task: app:ingress-nginx:install

  # config-managment addons

  config-managment:
    desc: Run all config-managment tasks
    cmds:
    - task: app:reloader:install
    - task: app:reflector:install
    - task: app:descheduler:install
  

  # secrets management | sealed-secrets 
  sealed-secrets:
    desc: Run all sealed-secrets tasks
    cmds:
    - task: k3d:cluster:create
    - task: app:sealed-secrets:install-kubeseal
    - task: app:sealed-secrets:create-private-key
    - kubectl apply -k .config/sealed-secrets
    - task: app:sealed-secrets:local-apply

  # policy enforcement | goldilocks
  goldilocks-minimal:
    desc: Run the goldilocks project
    cmds:
    - task: k3d:cluster:create
    - task: app:ingress-nginx:install
    - task: app:reflector:install
    - task: app:reloader:install
    - task: suite:goldilocks:install
    # - open https://goldilocks.k8s.localhost

  # policy enforcement | gatekeeper
  opa-gatekeeper:
    desc: Run the opa-gatekeeper project
    cmds:
    - task: goldilocks-minimal
    - task: suite:gatekeeper:full-run
    - task: suite:gatekeeper-pm:full-run
    # - open https://gpm.k8s.localhost
  
  # policy enforcement | gatekeeper
  opa-gatekeeper-demo:
    desc: Run the opa-gatekeeper project
    cmds:
    - task: suite:gatekeeper:create-constraint-teample
    - task: suite:gatekeeper:create-constraint
    - task: suite:gatekeeper:test-constraint-expect-failure
    - task: suite:gatekeeper:test-constraint-expect-success
  
  opa-gatekeeper-demo-cleanup:
    desc: Cleanup the opa-gatekeeper project
    cmds:
    - task: suite:gatekeeper:delete-constraint
    - task: suite:gatekeeper:delete-constraint-template

  # piplines | argo-workflows
  argo-workflows:
    desc: Run the argo-workflows project
    cmds:
    - task: config-managment
    - task: app:ingress-nginx:install
    - task: app:minio:full-run
    # - task: argo-wokrflows:full-run
    # - task: argo-wokrflows:secret
    # - task: argo-wokrflows:run-workflow  
  
  chartmeusem:
    desc: Run the chartmeusem project
    cmds:
    - task: app:chartmeusem:install-argo-app
  
  chartmeusem:cleanup:
    desc: Run the chartmeusem project
    cmds:
    - task: app:chartmeusem:rm
