version: '3'

# silent: true

dotenv:
- .env

includes:
  # utils
  helm: ./config/tasks/helm.yaml
  templates: ./config/tasks/templates.yaml
  # tests
  test: ./config/tasks/test.yaml
  # posts
  k3d: ./posts/k3d-intro/k3d-intro.yaml
  external-dns: ./posts/PGK-part-3/tasks.yaml
  coredns: ./posts/coredns/tasks.yaml
  argocd: ./posts/argocd/tasks.yaml
  ingress-nginx: ./posts/ingress-nginx/tasks.yaml
  # common tools for this repo
  tools: ./config/tasks/tools.yaml
  # common tools foor configuration managment   
  config-managment: ./posts/config/tasks.yaml
  vault: ./posts/vault-eso/tasks.yaml
  sealed-secrets: ./posts/sealed-secrets/Taskfile.yaml

  awx: ./posts/awx/tasks.yaml
  
  # applications / packages
  cicd-toolz: ./posts/cicd-toolz/tasks.yaml
  
  # helm chart registry
  chartmeusem: ./posts/chartmeusem/tasks.yaml
  
  # observability
  monitoring-n-logging: ./posts/monitoring-n-logging/tasks.yaml

tasks:

  cluster-create:
    desc: Start the k3d cluster
    cmds:
    - task: k3d:cluster-template
    - task: k3d:cluster-create
    - task: k3d:dns
    - task: k3d:certs

  external-dns:
    desc: Run the external-dns project
    cmds:
    - task: external-dns:pkg-part-3

  coredns:
    desc: Run the codedns project
    cmds:
    - task: coredns:dns-test

  argocd:
    desc: Deploy argocd project
    cmds:
    - task: argocd:install
    - task: argocd:secret
    - task: argocd:repo

  ingress-nginx:
    desc: Deploy nginx project
    cmds:
    - task: ingress-nginx:install-argocd-app

  config-managment:
    desc: Run all config-managment tasks
    cmds:
    - task: config-managment:install
  
  sealed-secrets:
    desc: Run all sealed-secrets tasks
    cmds:
    - task: cluster-create
    - task: sealed-secrets:install-kubeseal
    - task: sealed-secrets:create-private-key
    - kubectl apply -k .config/sealed-secrets
    - task: sealed-secrets:local-apply
    # - task: sealed-secrets:install-kubeseal
    # - task: sealed-secrets:create-private-key

  so-far:
    desc: Run core tasks
    cmds:
    - task: cluster-create
    - kubectl apply -k .config/tls
    - task: argocd
    - task: config-managment
    - task: nginx
    - task: chartmeusem:install-argo-app
    # - task: monitoring-n-logging:all

  run-tests:
    desc: Run tests
    cmds:
      - task: test:helm-wrapper

  destroy-env:
    desc: Destroy the k3d cluster
    cmds:
    - k3d cluster delete $CLUSTER_NAME

  help:
    desc: Show help
    cmds:
    - task --list

