apiVersion: v2
name: 'gatekeeper'
description: A Helm chart for wrapping gatekeeper
version: 0.1.0
appVersion: 0.1.0
dependencies:
  - name: 'gatekeeper'
    version: '3.16.3'
    repository: "https://open-policy-agent.github.io/gatekeeper/charts"
