---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:

  # image_pull_secrets: 
  # - regcred

  no_log: false
  ipv6_disabled: true
  # These parameters are designed for use with:
  # - AWX Operator: 0.20.0
  #   https://github.com/ansible/awx-operator/blob/0.20.0/README.md
  # - AWX: 20.1.0
  #   https://github.com/ansible/awx/blob/20.1.0/INSTALL.md

  image: quay.io/ansible/awx
  image_version: 23.8.1

  admin_user: admin
  admin_password_secret: awx-admin-password

  # create Classic Load Balancer
  # service_type: LoadBalancer

  postgres_configuration_secret: awx-postgres-configuration

  # ingress_type: none 
  ingress_type: ingress
  # ingress_path: "/"
  ingress_path_type: ImplementationSpecific
  # ingress_path_type: Prefix

  # # hostname value is used in the ALB Listener rules
  # # if host is equal to <hostname value> then traffic will be forwarded to Target Group
  ingress_class_name: nginx
  ingress_annotations: |
    kubernetes.io/ingress.class: nginx
  ingress_hosts:
    - hostname: awx.k8s.localhost
      tls_secret: tls-secret