---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-password
  namespace: default
spec:
  encryptedData:
    password.txt: AQCoJ1pK6d1XzZC3fWY3Ofv5BVxxCdsUYhkQUEcxWvZ3Z4I6S8ZR2q0iUsKj5aEqNnVdcP0XJGPLvJ36IH1GTZWldvnr9jHkORljYW1/GdVQF2VmxFk8iA8ifjnbsbVp6T4QaEBuCqW9OY56Jboo4j5jlyJa/iOAr6CjowcWSQZcLqg240AVtO2/q48tw6XIopn8uSM7hbe9JhGjcXnRsLmCKDDbElWiB59elpDR3vUbiKrhngyahgn5lbI/LB+Wke1wqo4FUmtDgLCnLkB/MZu01f52YLkzgp5BZS5bljl93Zqr5w1Io2CWDx6XZCOlkyA4KSTlSAKn4CM7tSKO9to0+zRvAnDMVwoLKpUE6AOah8nvdrj6ACbkxKGZz6Fx5Muo8a04WwLlWGg=
  template:
    metadata:
      creationTimestamp: null
      name: db-password
      namespace: default
