version: '3'

silent: true

includes:
  helm: ../../../config/tasks/helm.yaml

vars:
  rf_controller_name: &rfname reflector
  rf_controller_namespace: *rfname
  rf_controller_repo: https://emberstack.github.io/helm-charts
  rf_controller_chart_version: 7.0.193
  rf_local_registry: 'registry.localhost:5002'

tasks:

  install-dev:
    cmds:
      - task: set-argocd-context
      - task: dryrun
      - task: apply

  install:
    cmds:
      - task: dryrun
      - task: apply

  create-wrapper-chart:
    dir: '{{.ROOT_DIR}}/config/apps/'
    cmds:
      - task: helm:create-wrapper-chart
        vars:
          APP_WRAPPER_NAME: '{{.rf_controller_name}}'
          APP_NAME: '{{.rf_controller_name}}'
          APP_REPO: '{{.rf_controller_repo}}'
          APP_VERSION: '{{.rf_controller_chart_version}}'

  create-values:
    dir: '{{.ROOT_DIR}}/config/apps/{{.rf_controller_name}}'
    cmds:
      - |
        test -f values.yaml && mv values.yaml values.yaml.bak || true
        cat<<EOF > values.yaml
        {{.rf_controller_name}}: {}
        EOF
  
  dryrun:
    vars: &rfvars
      CHART: '{{.rf_controller_name}}'
      NAMESPACE: '{{.rf_controller_namespace}}'
      REPO_URL: '{{.rf_controller_repo}}'
      VERSION: '{{.rf_controller_chart_version}}'
      CHART_FOLDER: './config/apps/{{.rf_controller_name}}'
      VALUES_FILES: './config/apps/{{.rf_controller_name}}/values.yaml'
    cmds:
      - task: helm:repo_add
        vars: *rfvars
      - task: helm:dependency_build
        vars: *rfvars
      - task: helm:template
        vars: *rfvars
      - task: helm:template_apply_dry_run
        vars: *rfvars
  
  apply:
    cmds:
      - task: helm:dependency_build 
        vars: *rfvars
      - task: helm:install
        vars: *rfvars
  
  full-run:
    cmds:
      - test -d ./config/apps/{{.rf_controller_name}} && mv ./config/apps/{{.rf_controller_name}} ./config/apps/{{.rf_controller_name}}.bak || true
      - task: create-wrapper-chart
      - task: create-values
      - task: dryrun
      - task: apply
  
  test-controller:
    summary: Test the constraint by creating a namespace without the required label
    cmds:
      - echo "simulating the descheduler controller"
      - echo "This was tested manually on eks"
