apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: odiglet
subjects:
  - kind: ServiceAccount
    name: odiglet
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: odiglet
  apiGroup: rbac.authorization.k8s.io
