# File must be named k8s.yaml or k8s.yml
- name: Use default config (~/.kube/config) file and active context, and return objects for a specific namespace
  plugin: kubernetes.core.k8s
  connections:
    - namespaces:
        - default
# - name: Authenticate with token, and return all pods and services for all namespaces
#   plugin: kubernetes.core.k8s
#   connections:
#     - host: https://192.168.64.4:8443
#       api_key: xxxxxxxxxxxxxxxx
#       validate_certs: false
# - name: Use a custom config file, and a specific context.
#   plugin: kubernetes.core.k8s
#   connections:
#     - kubeconfig: /path/to/config
#       context: 'awx/192-168-64-4:8443/developer'
