version: '3'

silent: true

includes:
  helm: './../../config/tasks/helm.yaml'

vars:
  in_controller_name: &inname ingress-nginx
  in_controller_namespace: *inname
  in_controller_repo: https://kubernetes.github.io/ingress-nginx
  in_controller_chart_version: 4.10.0
  in_local_registry: 'registry.localhost:5002'
tasks:

  install-dev:
    cmds:
      - task: set-ns-context
      - task: dryrun
      - task: apply
      # - task: set-argocd-context
      # - task: install-argocd-app

  install:
    cmds:
      - task: dryrun
      - task: apply


  # helm 
  
  create-wrapper-chart:
    dir: '{{.ROOT_DIR}}/config/apps/'
    cmds:
      - task: helm:create-wrapper-chart
        vars:
          APP_WRAPPER_NAME: '{{.in_controller_name}}'
          APP_NAME: '{{.in_controller_name}}'
          APP_REPO: '{{.in_controller_repo}}'
          APP_VERSION: '{{.in_controller_chart_version}}'

  create-values:
    dir: '{{.ROOT_DIR}}/config/apps/{{.in_controller_name}}'
    cmds:
      - |
        # this are dev-values.yaml
        test -f values.yaml && mv values.yaml values.yaml.bak || true
        cat<<EOF > values.yaml
        {{.in_controller_name}}:
          controller:
            config:
              force-ssl-redirect: "true"
            extraArgs:
              default-ssl-certificate: "ingress-nginx/tls-secret"
            autoscaling:
              enabled: false
        EOF
  
  dryrun:
    vars: &invars
      CHART: '{{.in_controller_name}}'
      NAMESPACE: '{{.in_controller_namespace}}'
      REPO_URL: '{{.in_controller_repo}}'
      VERSION: '{{.in_controller_chart_version}}'
      CHART_FOLDER: './config/apps/{{.in_controller_name}}'
      VALUES_FILES: './config/apps/{{.in_controller_name}}/values.yaml'
    cmds:
      - task: helm:repo_add
        vars: *invars
      - task: helm:dependency_build
        vars: *invars
      - task: helm:template
        vars: *invars
      - task: helm:template_apply_dry_run
        vars: *invars
  
  apply:
    cmds:
      - task: helm:dependency_build 
        vars: *invars
      - task: helm:install
        vars: *invars
  
  full-run:
    cmds:
      - task: create-wrapper-chart
      - task: create-values
      - task: dryrun
      - task: apply

  set-ns-context:
    internal: true
    cmds:
    - kubectl config set-context --current --namespace {{.in_controller_namespace}} --cluster=k3d-{{.CLUSTER_NAME}}
  

  # with argocd

  install-argocd-app:
    desc: Installs nginx as argocCD application
    dir: config/apps/
    cmds:
    - task: set-argocd-context
    - kubectl apply -f {{.in_controller_name}}.yaml
  
  delete-argocd-app:
    dir: config/apps/
    cmds:
    - task: set-argocd-context
    - kubectl delete -f ingress-nginx.yaml
    ignore_error: true
  
  set-argocd-context:
    internal: true
    cmds:
    - kubectl config set-context --current --namespace=argocd --cluster=k3d-{{.CLUSTER_NAME}}
  
  