apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://gitlab.tikalk.dev/tikalk/users/hagzag/code-samples.git'
    path: config/apps/ingress-nginx
    targetRevision: main
    helm:
      releaseName: nginx
      values: |
        ingress-nginx:
          controller:
            config:
              force-ssl-redirect: "true"
            extraArgs:
              default-ssl-certificate: "ingress-nginx/tls-secret"
            autoscaling:
              enabled: false
          extraArgs:
            default-ssl-certificate: "ingress-nginx/tls-secret"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
