apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/kubernetes/ingress-nginx.git'
    path: charts/ingress-nginx
    targetRevision: main
    helm:
      releaseName: nginx
      values: |
        extraArgs:
          default-ssl-certificate: "ingress-nginx/tls-secret"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: -1
      backoff:
        duration: 60s
        factor: 2
        maxDuration: 30m
