apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/kubernetes/ingress-nginx.git'
    path: charts/ingress-nginx
    targetRevision: main
    helm:
      releaseName: nginx
      parameters:
      - name: "default-ssl-certificate"
        value: "kube-system/tls-secret"
      # values: |
      #   extraArgs:
      #     default-ssl-certificate: "kube-system/tls-secret"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=true
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: -1
      backoff:
        duration: 60s
        factor: 2
        maxDuration: 30m
