apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odigos
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitlab.tikalk.dev/tikalk/users/hagzag/code-samples.git
    targetRevision: main
    path: config/apps/odigos
  destination:
    namespace: odigos
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSyncOnly=false
    - Prune=true
    retry:
      limit: -1
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 30m
