version: '3'

silent: true

includes:
  helm: ../utils/helm.yaml

vars:
  whoami_controller_name: &whoaminame whoami
  whoami_controller_namespace: *whoaminame
  whoami_controller_repo: https://cowboysysop.github.io/charts/
  whoami_controller_chart_version: 5.1.0
  whoami_local_registry: 'registry.localhost:5002'
tasks:

  install-dev:
    cmds:
      - task: set-ns-context
      - task: dryrun
      - task: apply
      # - task: set-argocd-context
      # - task: install-argocd-app

  install:
    cmds:
      - task: dryrun
      - task: apply


  # helm 
  
  create-wrapper-chart:
    dir: '{{.ROOT_DIR}}/config/apps/'
    cmds:
      - task: helm:create-wrapper-chart
        vars:
          APP_WRAPPER_NAME: '{{.whoami_controller_name}}'
          APP_NAME: '{{.whoami_controller_name}}'
          APP_REPO: '{{.whoami_controller_repo}}'
          APP_VERSION: '{{.whoami_controller_chart_version}}'

  create-values:
    dir: '{{.ROOT_DIR}}/config/apps/{{.whoami_controller_name}}'
    cmds:
      - |
        # this are dev-values.yaml
        test -f values.yaml && mv values.yaml values.yaml.bak || true
        cat<<EOF > values.yaml
        {{.whoami_controller_name}}:
          ingress:
            enabled: true
            ingressClassName: nginx
            pathType: ImplementationSpecific
            annotations:
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            hosts:
              - host: &host whoami.k8s.localhost
                paths:
                  - /
            tls: 
              - secretName: tls-secret
                hosts:
                  - *host

          resources:
            # limits:
            #   cpu: 100m
            #   memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
        EOF
  
  dryrun:
    vars: &whoamivars
      CHART: '{{.whoami_controller_name}}'
      NAMESPACE: '{{.whoami_controller_namespace}}'
      REPO_URL: '{{.whoami_controller_repo}}'
      VERSION: '{{.whoami_controller_chart_version}}'
      CHART_FOLDER: './config/apps/{{.whoami_controller_name}}'
      VALUES_FILES: './config/apps/{{.whoami_controller_name}}/values.yaml'
    cmds:
      - task: helm:repo_add
        vars: *whoamivars
      - task: helm:dependency_build
        vars: *whoamivars
      - task: helm:template
        vars: *whoamivars
      - task: helm:template_apply_dry_run
        vars: *whoamivars
  
  apply:
    cmds:
      - task: helm:dependency_build 
        vars: *whoamivars
      - task: helm:install
        vars: *whoamivars
  
  full-run:
    cmds:
      - task: create-wrapper-chart
      - task: create-values
      - task: dryrun
      - task: apply

  set-ns-context:
    internal: true
    cmds:
    - kubectl config set-context --current --namespace {{.whoami_controller_namespace}} --cluster=k3d-{{.CLUSTER_NAME}}
  

  # with argocd

  install-argocd-app:
    desc: Installs nginx as argocCD application
    dir: config/apps/
    cmds:
    - task: set-argocd-context
    - kubectl apply -f {{.whoami_controller_name}}.yaml
  
  delete-argocd-app:
    dir: config/apps/
    cmds:
    - task: set-argocd-context
    - kubectl delete -f ingress-nginx.yaml
    ignore_error: true
  
  set-argocd-context:
    internal: true
    cmds:
    - kubectl config set-context --current --namespace=argocd --cluster=k3d-{{.CLUSTER_NAME}}
  
  
