version: '3'  
includes:
  # utils
  helm: ./helm.yaml

tasks:
  
  helm-wrapper:
    cmds:
      - task: helm:create-wrapper-chart
        vars:
          APP_WRAPPER_NAME: 'my-chart-wrapper-test'
          APP_NAME: 'my-chart-test'
          APP_REPO: 'https://localhost:8080/chart-repo/my-chart'
          APP_VERSION: '0.2.0'