goldilocks:
  image:
    # image.repository -- Repository for the goldilocks image
    repository: us-docker.pkg.dev/fairwinds-ops/oss/goldilocks
    # image.tag -- The goldilocks image tag to use
    tag: v4.10.0
  # For testing, make sure to install the vpa and metrics-server as sub-charts
  vpa:
    enabled: true
  controller:
    flags:
      on-by-default: true
      exclude-namespaces: kube-system
    deployment:
      additionalLabels:
        test: value
      podAnnotations:
        foo: bar
    rbac:
      extraRules:
        - apiGroups:
            - "batch"
          resources:
            - "*"
          verbs:
            - "get"
            - "list"
            - "watch"
      extraClusterRoleBindings:
        - view
  dashboard:
    basePath: /
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: &host goldilocks.k8s.localhost
          paths:
            - path: /
              type: ImplementationSpecific
      tls:
        - secretName: tls-secret
          hosts:
            - *host
    replicaCount: 1
