version: '3'

silent: true


includes:
  helm: ../../config/tasks/helm.yaml

tasks:


  dockercondig-secret-clenup:
    silent: true
    dir: .config/docker-config
    cmds:
    - kubectl delete secret regcred

  dockercondig-secret:
    silent: true
    dir: .config/docker-config
    requires:
      vars: [ DOCKER_USERNAME, DOCKER_PASSWORD, DOCKER_EMAIL ]
    vars:
      DOCKER_AUTH:
        sh: echo -n {{.DOCKER_USERNAME}}:{{.DOCKER_PASSWORD}} | base64
    desc: Create a dockerconfig secret
    cmds:
    - |
      cat <<EOF>.dockerconfig.json
      {
        "auths": {
          "{{.DOCKER_REGISTRY}}": {
            "username": "{{.DOCKER_USERNAME}}",
            "password": "{{.DOCKER_PASSWORD}}",
            "email": "{{.DOCKER_EMAIL}}",
            "auth": "{{.DOCKER_AUTH}}"
          }
        }
      }
      EOF
    - |
      kubectl create secret docker-registry \
      regcred --docker-server=docker.io --docker-username=$DOCKER_USERNAME \
      --docker-password=$DOCKER_PASSWORD --docker-email=$DOCKER_EMAIL

  install:
    desc: Installs reloader + scheduler resources manually on the local cluster
    dir: config/apps/
    cmds:
    - kubectl apply -f reloader.yaml
    - kubectl apply -f reflector.yaml
    - kubectl apply -f descheduler.yaml

  rm:
    dir: config/apps/
    cmds:
    - delete -f nginx.yaml
    ignore_error: true

  # install reloader via helm chart + argocd-app
  reloader-local-dryrun:
    vars: &reloader-vars
      CHART: &reloader-name reloader
      NAMESPACE: *reloader-name
      REPO_URL:
       sh: cat ./config/apps/reloader/Chart.yaml | yq .dependencies.[0].repository
      VERSION:
       sh: cat ./config/apps/reloader/Chart.yaml | yq .dependencies.[0].version
      CHART_FOLDER: '{{.ROOT_DIR}}/config/apps/reloader'
      VALUES_FILES: '{{.ROOT_DIR}}/config/apps/reloader/values.yaml'
    cmds:
      - task: helm:repo_add
        vars: *reloader-vars
      - task: helm:dependency_build 
        vars: *reloader-vars
      - task: helm:template
        vars: *reloader-vars
      - task: helm:template_apply_dry_run
        vars: *reloader-vars

  reloader-local-apply:
    cmds:
      - task: helm:dependency_build 
        vars: *reloader-vars
      - task: helm:install
        vars: *reloader-vars
  
  # install reflector via helm chart + argocd-app
  reflector-local-dryrun:
    vars: &reflector-vars
      CHART: &reflector-name reflector
      NAMESPACE: *reflector-name
      REPO_URL:
       sh: cat ./config/apps/reflector/Chart.yaml | yq .dependencies.[0].repository
      VERSION:
       sh: cat ./config/apps/reflector/Chart.yaml | yq .dependencies.[0].version
      CHART_FOLDER: '{{.ROOT_DIR}}/config/apps/reflector'
      VALUES_FILES: '{{.ROOT_DIR}}/config/apps/reflector/values.yaml'
    cmds:
      - task: helm:repo_add
        vars: *reflector-vars
      - task: helm:dependency_build 
        vars: *reflector-vars
      - task: helm:template
        vars: *reflector-vars
      - task: helm:template_apply_dry_run
        vars: *reflector-vars

  reflector-local-apply:
    cmds:
      - task: helm:dependency_build 
        vars: *reflector-vars
      - task: helm:install
        vars: *reflector-vars

  # install descheduler via helm chart + argocd-app
  descheduler-local-dryrun:
    vars: &descheduler-vars
      CHART: &descheduler-name descheduler
      NAMESPACE: *descheduler-name
      REPO_URL:
       sh: cat ./config/apps/descheduler/Chart.yaml| yq .dependencies.[0].repository
      VERSION:
       sh: cat ./config/apps/descheduler/Chart.yaml | yq .dependencies.[0].version
      CHART_FOLDER: "{{.ROOT_DIR}}/config/apps/descheduler"
      VALUES_FILES: '{{.ROOT_DIR}}/config/apps/descheduler/values.yaml'
    cmds:
      - task: helm:repo_add
        vars: *descheduler-vars
      - task: helm:dependency_build 
        vars: *descheduler-vars
      - task: helm:template
        vars: *descheduler-vars
      - task: helm:template_apply_dry_run
        vars: *descheduler-vars

  descheduler-local-apply:
    cmds:
      - task: helm:dependency_build 
        vars: *descheduler-vars
      - task: helm:install
        vars: *descheduler-vars

  
  whoami-local-dryrun:
    vars: &whoami-vars
      CHART: &whoami-name whoami
      NAMESPACE: *whoami-name
      REPO_URL:
       sh: cat ./config/apps/whoami/Chart.yaml| yq .dependencies.[0].repository
      VERSION:
       sh: cat ./config/apps/whoami/Chart.yaml | yq .dependencies.[0].version
      CHART_FOLDER: "{{.ROOT_DIR}}/config/apps/whoami"
      VALUES_FILES: '{{.ROOT_DIR}}/config/apps/whoami/values.yaml'
    cmds:
      - task: helm:repo_add
        vars: *whoami-vars
      - task: helm:dependency_build 
        vars: *whoami-vars
      - task: helm:template
        vars: *whoami-vars
      - task: helm:template_apply_dry_run
        vars: *whoami-vars

  whoami-local-apply:
    cmds:
      - task: helm:dependency_build 
        vars: *whoami-vars
      - task: helm:install
        vars: *whoami-vars

  